CX = cx
CXFLAGS =

all:
	$(CX) $(CXFLAGS) \
	pkg/phx/vector.cx \
	pkg/phx/direction.cx \
	\
	pkg/graphical3d/graphical.cx \
	pkg/graphical3d/planeGeometry.cx \
	\
	internal/app.cx \
	internal/loop_limiter.cx \
	internal/loop_tracker.cx \
	\
	internal/player.cx \
	internal/brick.cx \
	internal/ball.cx \
	internal/game.cx \
	\
	cmd/main.cx
