CX = cx
CXFLAGS =

all:
	$(CX) $(CXFLAGS) \
	\
	internal/app.cx \
	internal/collision.cx \
	internal/inputs.cx \
	internal/loop_limiter.cx \
	internal/loop_tracker.cx \
	internal/sprites.cx \
	\
	cmd/main.cx
