run:
	cx\
		pkg/graphical2d/graphical.cx\
		pkg/graphical2d/screens.cx\
		pkg/phx/vector.cx\
		pkg/phx/direction.cx\
		\
		pkg/graphical3d/graphical.cx\
		pkg/graphical3d/boxGeometry.cx\
		pkg/graphical3d/sphereGeometry.cx\
		pkg/graphical3d/cylinderGeometry.cx\
		pkg/graphical3d/circleGeometry.cx\
		\
		internal/models/timer.cx\
		internal/models/cell.cx\
		internal/models/point.cx\
		internal/models/board.cx\
		internal/models/player.cx\
		internal/models/ghost.cx\
		internal/models/game.cx\
		\
		internal/domain/scene/scene.cx\
		internal/domain/scene/game/game-scene.cx\
		internal/domain/scene/game/home-scene.cx\
		internal/domain/scene/game/select-player-scene.cx\
		internal/domain/scene/game/select-board-scene.cx\
		internal/domain/scene/game/select-points-scene.cx\
		internal/domain/scene/game/settings-scene.cx\
		\
		cmd/main.cx
