CX = cx
CXFLAGS =

all:
	$(CX) $(CXFLAGS) \
	pkg/phx/vector.cx \
	pkg/phx/direction.cx \
	pkg/graphical3d/graphical.cx \
	pkg/graphical3d/planeGeometry.cx \
	\
	internal/window.cx \
	internal/sprite.cx \
	internal/bird.cx \
	internal/pipe.cx \
	internal/game.cx \
	\
	cmd/main.cx \
